# Generated by Django 4.2.6 on 2023-10-18 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='actuality',
            field=models.CharField(choices=[('Актуален', 'Актуален'), ('50 на 50', '50 на 50'), ('Стрем', 'Стрем')], default=('Актуален', 'Актуален'), max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='video',
            field=models.URLField(null=True),
        ),
        migrations.CreateModel(
            name='ReviewBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_review', models.TextField()),
                ('rate_stars', models.CharField(choices=[('*', '*'), ('**', '**'), ('***', '***'), ('****', '****'), ('*****', '*****')], max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_object', to='book.book')),
            ],
        ),
    ]
